version: '3'
services:
  frontend:
    build:
      context: ./frontend_api_service
    container_name: frontend_api_service
    ports:
      - "8001:8001"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend_api_service
    container_name: backend_api_service
    ports:
      - "8000:8000"
    
